Args = --no-fallback \
       -H:EnableURLProtocols=http,https \
       --report-unsupported-elements-at-runtime \
       --enable-native-access=ALL-UNNAMED \
       --initialize-at-build-time=org.slf4j.LoggerFactory \
       --initialize-at-run-time=io.netty.util.internal.logging.Log4JLogger \
       --initialize-at-run-time=com.sun.jna.Native \
       --initialize-at-run-time=com.sun.jna.Structure \
       --initialize-at-run-time=com.sun.jna.Memory \
       --initialize-at-run-time=com.sun.jna.Pointer
